# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mhidou.io - A full stack developer diary
email: mehdi@mhidou.io
description: > # this means to ignore newlines until "baseurl:"
  I'm Mehdi Ahraoui, an indie full stack developer, in this blog I will try to share my experience on web, mobile and software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mhidou.github.io" # the base hostname & protocol for your site
twitter_username: mehdi_ahraoui
github_username:  mhidou

# Build settings
markdown: kramdown
